FROM python:3.12-slim-bookworm
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        python3-dev \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY ./niftron /app/niftron

CMD ["uvicorn", "niftron.api.main:app", "--host", "0.0.0.0", "--port", "8000"]